# ...new docker image Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodemo
  template:
    metadata:
      labels:
        app: mongodemo
    spec:
      containers:
        - name: app
          image: 8979635092/test:latest
          ports:
            - containerPort: 8082
          env:
            - name: spring.data.mongodb.host
              value: mongodemodb
          imagePullPolicy: Always
---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: mongodemo
spec:
  selector:
    app: mongodemo
  ports:
    - port: 8082
      targetPort: 8082
  type: LoadBalancer
