apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodemodb
spec:
  selector:
    app: mongodemodb
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodemodb
spec:
  selector:
    matchLabels:
      app: mongodemodb
  template:
    metadata:
      labels:
        app: mongodemodb
    spec:
      containers:
        - name: mongodemodb
          image: mongo:3.2.4
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc